version: "3.9"
services:
  mysql-container:
    image: mysql
    restart: always
    ports:
      - 10001:3306
    environment:
      - MYSQL_DATABASE=testing
      - MYSQL_ROOT_PASSWORD=rajat123
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db-data:/var/lib/mysql/
  rest-jwt:
    image: rest-jwt:1.0
    restart: always
    depends_on:
      - mysql-container
    ports:
      - 3000:3000
    command: sh -c 'until nc -z mysql-container 3306; do echo "Waiting for MySQL to be ready..."; sleep 1; done && npm start'
  front-end:
    image: front-end:1.0
    restart: always
    depends_on:
      - mysql-container
      - rest-jwt
    ports:
      - 3001:3000
volumes:
  db-data:
    driver: local
